# SPDX-FileCopyrightText: 2026 Trijal Saha <trijalsaha2012@gmail.com>
# SPDX-License-Identifier: GPL-2.0-or-later

[Device]
name=Google Pixel 9 Pro XL

[Panels]
statusBarHeight=190
navigationPanelHeight=170
leftPadding=50
rightPadding=50

[Panels][Top]
centerSpacing=90
